# Site
title:              Taufiqurrahman
bio:                'Hai, Nama saya Taufiqurrahman, Mahasiswa <a href="http://sif.uin-suska.ac.id/">Jurusan Sistem Informasi</a> Fakultas Sains dan Teknologi di <a href="http://uin-suska.ac.id/">UIN Suska Riau</a>.'
description:        "Ini adalah Git Page Pertama saya menggunakan tema dari Jekyll."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/aku.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://taufiqurrahmantaufiqq.github.io/tfqprofill

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taufiq

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              taufiqurrahmantaufiqq@gmail.com
#twitter:            username
facebook:           taufiqurrahman22
github-url:         taufiqurrahmantaufiqq
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          taufiqurrahman_022
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
